<a href="https://colab.research.google.com/github/SaraGallego22/Optimizacion-II/blob/main/TOPSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TOPSIS ALGORTHM**


Topsis n=2

In [ ]:
import numpy as np
import warnings


class Topsis():
    evaluation_matrix = np.array([])  # Matrix
    weighted_normalized = np.array([])  # Weight matrix
    normalized_decision = np.array([])  # Normalisation matrix
    M = 0  # Number of rows
    N = 0  # Number of columns


    def __init__(self, evaluation_matrix, weight_matrix, criteria):
        # M×N matrix
        self.evaluation_matrix = np.array(evaluation_matrix, dtype="float")

        # M alternatives (options)
        self.row_size = len(self.evaluation_matrix)

        # N attributes/criteria
        self.column_size = len(self.evaluation_matrix[0])

        # N size weight matrix
        self.weight_matrix = np.array(weight_matrix, dtype="float")
        self.weight_matrix = self.weight_matrix/sum(self.weight_matrix)
        self.criteria = np.array(criteria, dtype="float")

        self.worst_alternatives= [0.39, 0.003, 0.036 ,0.056, 0.001,0.014, 0.021, 0.008, 0.005, 0.003]
        self.best_alternatives = [0.088, 0.067, 0.072, 0.074, 0.065, 0.077, 0.105, 0.073, 0.058, 0.03]
  '''
  Step 2
  '''
    def step_2(self):
        # normalized scores
        self.normalized_decision = np.copy(self.evaluation_matrix)
        sqrd_sum = np.zeros(self.column_size)
        for i in range(self.row_size):
            for j in range(self.column_size):
                sqrd_sum[j] += self.evaluation_matrix[i, j]**2
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.normalized_decision[i,
                                         j] = self.evaluation_matrix[i, j]/(sqrd_sum[j]**0.5)



    def step_3(self):
        from pdb import set_trace
        self.weighted_normalized = np.copy(self.normalized_decision)
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.weighted_normalized[i, j] *= self.weight_matrix[j]

    '''
	# Step 4
	Determine the worst alternative {\displaystyle (A_{w})}(A_{w}) and the best alternative {\displaystyle (A_{b})}(A_{b}):
	'''

    def step_4(self):
        self.worst_alternatives = np.zeros(self.column_size)
        self.best_alternatives = np.zeros(self.column_size)
        for i in range(self.column_size):
            if self.criteria[i]:
                self.worst_alternatives[i] = min(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = max(self.weighted_normalized[:, i])
            else:
                self.worst_alternatives[i] = max(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = min(self.weighted_normalized[:, i])

    '''
	# Step 5
	Calculate the L2-distance between the target alternative {\displaystyle i}i and the worst condition {\displaystyle A_{w}}A_{w}
	{\displaystyle d_{iw}={\sqrt {\sum _{j=1}^{n}(t_{ij}-t_{wj})^{2}}},\quad i=1,2,\ldots ,m,}
	and the distance between the alternative {\displaystyle i}i and the best condition {\displaystyle A_{b}}A_b
	{\displaystyle d_{ib}={\sqrt {\sum _{j=1}^{n}(t_{ij}-t_{bj})^{2}}},\quad i=1,2,\ldots ,m}
	where {\displaystyle d_{iw}}d_{{iw}} and {\displaystyle d_{ib}}d_{{ib}} are L2-norm distances 
	from the target alternative {\displaystyle i}i to the worst and best conditions, respectively.
	'''

    def step_5(self):
        self.worst_distance = np.zeros(self.row_size)
        self.best_distance = np.zeros(self.row_size)

        self.worst_distance_mat = np.copy(self.weighted_normalized)
        self.best_distance_mat = np.copy(self.weighted_normalized)
        self.worst_alternatives= [0.39, 0.003, 0.036 ,0.056, 0.001,0.014, 0.021, 0.008, 0.005, 0.003]
        self.best_alternatives = [0.088, 0.067, 0.072, 0.074, 0.065, 0.077, 0.105, 0.073, 0.058, 0.03]

        print(len(self.weighted_normalized), len(self.worst_alternatives), len(self.best_alternatives))
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.worst_distance_mat[i][j] = (self.weighted_normalized[i][j]-self.worst_alternatives[j])**2
                self.best_distance_mat[i][j] = (self.weighted_normalized[i][j]-self.best_alternatives[j])**2
                
                self.worst_distance[i] += self.worst_distance_mat[i][j]
                self.best_distance[i] += self.best_distance_mat[i][j]

        for i in range(self.row_size):
            self.worst_distance[i] = self.worst_distance[i]**0.5
            self.best_distance[i] = self.best_distance[i]**0.5

    '''
	# Step 6
	Calculate the similarity
	'''

    def step_6(self):
        np.seterr(all='ignore')
        self.worst_similarity = np.zeros(self.row_size)
        self.best_similarity = np.zeros(self.row_size)

        for i in range(self.row_size):
            # calculate the similarity to the worst condition
            self.worst_similarity[i] = self.worst_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])

            # calculate the similarity to the best condition
            self.best_similarity[i] = self.best_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])
    
    def ranking(self, data):
        return [i+1 for i in data.argsort()]

    def rank_to_worst_similarity(self):
        # return rankdata(self.worst_similarity, method="min").astype(int)
        return self.ranking(self.worst_similarity)

    def rank_to_best_similarity(self):
        # return rankdata(self.best_similarity, method='min').astype(int)
        return self.ranking(self.best_similarity)

    def calc(self):
        print("Step 1\n", self.evaluation_matrix, end="\n\n")
        self.step_2()
        print("Step 2\n", self.normalized_decision, end="\n\n")
        self.step_3()
        print("Step 3\n", self.weighted_normalized, end="\n\n")
        #self.step_4()
        #print("Step 4\n", self.worst_alternatives,
              #self.best_alternatives, end="\n\n")
        self.step_5()
        print("Step 5\n", self.worst_distance, self.best_distance, end="\n\n")
        self.step_6()
        print("Step 6\n", self.worst_similarity,
              self.best_similarity, end="\n\n")

In [ ]:
import numpy as np

evaluation_matrix = np.array([
                [7, 15, 12, 34, 9, 2, 5,8, 40, 17],   #a1
                [5, 14, 20, 26, 9, 2, 4, 15, 22, 16],   #a2
                [11, 19, 21, 31, 1, 11, 4, 42, 14, 18],   #a3
                [13, 1, 24, 27, 35, 6, 1, 5, 4, 2],   #a4
                ])

weights = [0.13, 0.1, 0.12, 0.13, 0.07, 0.09, 0.16, 0.08, 0.07, 0.05]

'''
if higher value is preferred - True
if lower value is preferred - False
'''
criterias = np.array([True, True, True, True])

t = Topsis(evaluation_matrix, weights, criterias)

t.calc()

print("best_distance\t", t.best_distance)
print("worst_distance\t", t.worst_distance)

# print("weighted_normalized",t.weighted_normalized)

print("worst_similarity\t", t.worst_similarity)
print("rank_to_worst_similarity\t", t.rank_to_worst_similarity())

print("best_similarity\t", t.best_similarity)
print("rank_to_best_similarity\t", t.rank_to_best_similarity())

Step 1
 [[ 7. 15. 12. 34.  9.  2.  5.  8. 40. 17.]
 [ 5. 14. 20. 26.  9.  2.  4. 15. 22. 16.]
 [11. 19. 21. 31.  1. 11.  4. 42. 14. 18.]
 [13.  1. 24. 27. 35.  6.  1.  5.  4.  2.]]

Step 2
 [[0.36689969 0.53605627 0.30372448 0.57290715 0.24157266 0.15569979
  0.65653216 0.175496   0.83478387 0.57536283]
 [0.26207121 0.50031918 0.50620746 0.43810547 0.24157266 0.15569979
  0.52522573 0.32905499 0.45913113 0.54151795]
 [0.57655666 0.67900461 0.53151784 0.52235652 0.02684141 0.85634884
  0.52522573 0.92135399 0.29217435 0.6092077 ]
 [0.68138514 0.03573708 0.60744896 0.45495568 0.93944922 0.46709937
  0.13130643 0.109685   0.08347839 0.06768974]]

Step 3
 [[0.04769696 0.05360563 0.03644694 0.07447793 0.01691009 0.01401298
  0.10504515 0.01403968 0.05843487 0.02876814]
 [0.03406926 0.05003192 0.0607449  0.05695371 0.01691009 0.01401298
  0.08403612 0.0263244  0.03213918 0.0270759 ]
 [0.07495237 0.06790046 0.06378214 0.06790635 0.0018789  0.0770714
  0.08403612 0.07370832 0.0204522  0.030460

Topsis n=1


In [ ]:
import numpy as np
import warnings


class Topsis():
    evaluation_matrix = np.array([])  # Matrix
    weighted_normalized = np.array([])  # Weight matrix
    normalized_decision = np.array([])  # Normalisation matrix
    M = 0  # Number of rows
    N = 0  # Number of columns

    '''
	Create an evaluation matrix consisting of m alternatives and n criteria,
	with the intersection of each alternative and criteria given as {\displaystyle x_{ij}}x_{ij},
	we therefore have a matrix {\displaystyle (x_{ij})_{m\times n}}(x_{{ij}})_{{m\times n}}.
	'''

    def __init__(self, evaluation_matrix, weight_matrix, criteria):
        # M×N matrix
        self.evaluation_matrix = np.array(evaluation_matrix, dtype="float")

        # M alternatives (options)
        self.row_size = len(self.evaluation_matrix)

        # N attributes/criteria
        self.column_size = len(self.evaluation_matrix[0])

        # N size weight matrix
        self.weight_matrix = np.array(weight_matrix, dtype="float")
        self.weight_matrix = self.weight_matrix/sum(self.weight_matrix)
        self.criteria = np.array(criteria, dtype="float")

        self.best_alternatives= [0.046, 0.038, 0.037, 0.37, 0.045, 0.047, 0.057, 0.048, 0.035, 0.016]
        self.worst_alternatives = [0.01, 0.002, 0.018, 0.028, 0.001, 0.008, 0.011, 0.0057, 0.003, 0.001]

    '''
	# Step 2
	The matrix {\displaystyle (x_{ij})_{m\times n}}(x_{{ij}})_{{m\times n}} is then normalised to form the matrix
	'''

    def step_2(self):
        # normalized scores
        self.normalized_decision = np.copy(self.evaluation_matrix)
        sqrd_sum = np.zeros(self.column_size)
        for i in range(self.row_size):
            for j in range(self.column_size):
                sqrd_sum[j] += self.evaluation_matrix[i, j]
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.normalized_decision[i,
                                         j] = self.evaluation_matrix[i, j]/(sqrd_sum[j])

    '''
	# Step 3
	Calculate the weighted normalised decision matrix
	'''

    def step_3(self):
        from pdb import set_trace
        self.weighted_normalized = np.copy(self.normalized_decision)
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.weighted_normalized[i, j] *= self.weight_matrix[j]



    def step_4(self):
        self.worst_alternatives = np.zeros(self.column_size)
        self.best_alternatives = np.zeros(self.column_size)
        for i in range(self.column_size):
            if self.criteria[i]:
                self.worst_alternatives[i] = min(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = max(self.weighted_normalized[:, i])
            else:
                self.worst_alternatives[i] = max(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = min(self.weighted_normalized[:, i])


    def step_5(self):
        self.worst_distance = np.zeros(self.row_size)
        self.best_distance = np.zeros(self.row_size)

        self.worst_distance_mat = np.copy(self.weighted_normalized)
        self.best_distance_mat = np.copy(self.weighted_normalized)
        self.best_alternatives= [0.046, 0.038, 0.037, 0.37, 0.045, 0.047, 0.057, 0.048, 0.035, 0.016]
        self.worst_alternatives = [0.01, 0.002, 0.018, 0.028, 0.001, 0.008, 0.011, 0.0057, 0.003, 0.001]

        print(len(self.weighted_normalized), len(self.worst_alternatives), len(self.best_alternatives))
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.worst_distance_mat[i][j] = abs(self.weighted_normalized[i][j]-self.worst_alternatives[j])
                self.best_distance_mat[i][j] = abs(self.weighted_normalized[i][j]-self.best_alternatives[j])
                
                self.worst_distance[i] += self.worst_distance_mat[i][j]
                self.best_distance[i] += self.best_distance_mat[i][j]

        for i in range(self.row_size):
            self.worst_distance[i] = self.worst_distance[i]
            self.best_distance[i] = self.best_distance[i]

    def step_6(self):
        np.seterr(all='ignore')
        self.worst_similarity = np.zeros(self.row_size)
        self.best_similarity = np.zeros(self.row_size)

        for i in range(self.row_size):
            # calculate the similarity to the worst condition
            self.worst_similarity[i] = self.worst_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])

            # calculate the similarity to the best condition
            self.best_similarity[i] = self.best_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])
    
    def ranking(self, data):
        return [i+1 for i in data.argsort()]

    def rank_to_worst_similarity(self):
        # return rankdata(self.worst_similarity, method="min").astype(int)
        return self.ranking(self.worst_similarity)

    def rank_to_best_similarity(self):
        # return rankdata(self.best_similarity, method='min').astype(int)
        return self.ranking(self.best_similarity)

    def calc(self):
        print("Step 1\n", self.evaluation_matrix, end="\n\n")
        self.step_2()
        print("Step 2\n", self.normalized_decision, end="\n\n")
        self.step_3()
        print("Step 3\n", self.weighted_normalized, end="\n\n")
        #self.step_4()
        #print("Step 4\n", self.worst_alternatives,
              #self.best_alternatives, end="\n\n")
        self.step_5()
        print("Step 5\n", self.worst_distance, self.best_distance, end="\n\n")
        self.step_6()
        print("Step 6\n", self.worst_similarity,
              self.best_similarity, end="\n\n")

In [ ]:
import numpy as np

evaluation_matrix = np.array([
                [7, 15, 12, 34, 9, 2, 5,8, 40, 17],   #a1
                [5, 14, 20, 26, 9, 2, 4, 15, 22, 16],   #a2
                [11, 19, 21, 31, 1, 11, 4, 42, 14, 18],   #a3
                [13, 1, 24, 27, 35, 6, 1, 5, 4, 2],   #a4
                ])

weights = [0.13, 0.1, 0.12, 0.13, 0.07, 0.09, 0.16, 0.08, 0.07, 0.05]

'''
if higher value is preferred - True
if lower value is preferred - False
'''
criterias = np.array([True, True, True, True])

t = Topsis(evaluation_matrix, weights, criterias)

t.calc()

print("best_distance\t", t.best_distance)
print("worst_distance\t", t.worst_distance)

# print("weighted_normalized",t.weighted_normalized)

print("worst_similarity\t", t.worst_similarity)
print("rank_to_worst_similarity\t", t.rank_to_worst_similarity())

print("best_similarity\t", t.best_similarity)
print("rank_to_best_similarity\t", t.rank_to_best_similarity())

Step 1
 [[ 7. 15. 12. 34.  9.  2.  5.  8. 40. 17.]
 [ 5. 14. 20. 26.  9.  2.  4. 15. 22. 16.]
 [11. 19. 21. 31.  1. 11.  4. 42. 14. 18.]
 [13.  1. 24. 27. 35.  6.  1.  5.  4.  2.]]

Step 2
 [[0.19444444 0.30612245 0.15584416 0.28813559 0.16666667 0.0952381
  0.35714286 0.11428571 0.5        0.32075472]
 [0.13888889 0.28571429 0.25974026 0.22033898 0.16666667 0.0952381
  0.28571429 0.21428571 0.275      0.30188679]
 [0.30555556 0.3877551  0.27272727 0.26271186 0.01851852 0.52380952
  0.28571429 0.6        0.175      0.33962264]
 [0.36111111 0.02040816 0.31168831 0.22881356 0.64814815 0.28571429
  0.07142857 0.07142857 0.05       0.03773585]]

Step 3
 [[0.02527778 0.03061224 0.0187013  0.03745763 0.01166667 0.00857143
  0.05714286 0.00914286 0.035      0.01603774]
 [0.01805556 0.02857143 0.03116883 0.02864407 0.01166667 0.00857143
  0.04571429 0.01714286 0.01925    0.01509434]
 [0.03972222 0.03877551 0.03272727 0.03415254 0.0012963  0.04714286
  0.04571429 0.048      0.01225    0.0169811

Topsis n=inf


In [ ]:
import numpy as np
import warnings


class Topsis():
    evaluation_matrix = np.array([])  # Matrix
    weighted_normalized = np.array([])  # Weight matrix
    normalized_decision = np.array([])  # Normalisation matrix
    M = 0  # Number of rows
    N = 0  # Number of columns

    def __init__(self, evaluation_matrix, weight_matrix, criteria):
        # M×N matrix
        self.evaluation_matrix = np.array(evaluation_matrix, dtype="float")

        # M alternatives (options)
        self.row_size = len(self.evaluation_matrix)

        # N attributes/criteria
        self.column_size = len(self.evaluation_matrix[0])

        # N size weight matrix
        self.weight_matrix = np.array(weight_matrix, dtype="float")
        self.weight_matrix = self.weight_matrix/sum(self.weight_matrix)
        self.criteria = np.array(criteria, dtype="float")

        self.best_alternatives= [0.046, 0.038, 0.037, 0.37, 0.045, 0.047, 0.057, 0.048, 0.035, 0.016]
        self.worst_alternatives = [0.01, 0.002, 0.018, 0.028, 0.001, 0.008, 0.011, 0.0057, 0.003, 0.001]


    def step_2(self):
        # normalized scores
        maximos=[13,19,24,34,35,11,5,42,30,18]
        self.normalized_decision = np.copy(self.evaluation_matrix)
        sqrd_sum = np.zeros(self.column_size)
        for i in range(self.row_size):
            for j in range(self.column_size):
                sqrd_sum[j] += self.evaluation_matrix[i, j]
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.normalized_decision[i,j] = self.evaluation_matrix[i, j]/(maximos[j])


    def step_3(self):
        from pdb import set_trace
        self.weighted_normalized = np.copy(self.normalized_decision)
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.weighted_normalized[i, j] *= self.weight_matrix[j]


    def step_4(self):
        self.worst_alternatives = np.zeros(self.column_size)
        self.best_alternatives = np.zeros(self.column_size)
        for i in range(self.column_size):
            if self.criteria[i]:
                self.worst_alternatives[i] = min(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = max(self.weighted_normalized[:, i])
            else:
                self.worst_alternatives[i] = max(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = min(self.weighted_normalized[:, i])

    def step_5(self):
        self.worst_distance = np.zeros(self.row_size)
        self.best_distance = np.zeros(self.row_size)

        self.worst_distance_mat = np.copy(self.weighted_normalized)
        self.best_distance_mat = np.copy(self.weighted_normalized)
        self.best_alternatives= [0.13, 0.1, 0.12, 0.13, 0.07, 0.09, 0.16, 0.08, 0.093, 0.05]
        self.worst_alternatives = [0.05, 0.005, 0.006, 0.099, 0.002, 0.016, 0.032, 0.009, 0.009,0.0055]

        print(len(self.weighted_normalized), len(self.worst_alternatives), len(self.best_alternatives))
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.worst_distance_mat[i][j] = abs(self.weighted_normalized[i][j]-self.worst_alternatives[j])
                self.best_distance_mat[i][j] = abs(self.weighted_normalized[i][j]-self.best_alternatives[j])
                
                self.worst_distance[i] += self.worst_distance_mat[i][j]
                self.best_distance[i] += self.best_distance_mat[i][j]

        for i in range(self.row_size):
            self.worst_distance[i] = self.worst_distance[i]
            self.best_distance[i] = self.best_distance[i]

    def step_6(self):
        np.seterr(all='ignore')
        self.worst_similarity = np.zeros(self.row_size)
        self.best_similarity = np.zeros(self.row_size)

        for i in range(self.row_size):
            # calculate the similarity to the worst condition
            self.worst_similarity[i] = self.worst_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])

            # calculate the similarity to the best condition
            self.best_similarity[i] = self.best_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])
    
    def ranking(self, data):
        return [i+1 for i in data.argsort()]

    def rank_to_worst_similarity(self):
        # return rankdata(self.worst_similarity, method="min").astype(int)
        return self.ranking(self.worst_similarity)

    def rank_to_best_similarity(self):
        # return rankdata(self.best_similarity, method='min').astype(int)
        return self.ranking(self.best_similarity)

    def calc(self):
        print("Step 1\n", self.evaluation_matrix, end="\n\n")
        self.step_2()
        print("Step 2\n", self.normalized_decision, end="\n\n")
        self.step_3()
        print("Step 3\n", self.weighted_normalized, end="\n\n")
        #self.step_4()
        #print("Step 4\n", self.worst_alternatives,
              #self.best_alternatives, end="\n\n")
        self.step_5()
        print("Step 5\n", self.worst_distance, self.best_distance, end="\n\n")
        self.step_6()
        print("Step 6\n", self.worst_similarity,
              self.best_similarity, end="\n\n")

In [ ]:
import numpy as np

evaluation_matrix = np.array([
                [7, 15, 12, 34, 9, 2, 5,8, 40, 17],   #a1
                [5, 14, 20, 26, 9, 2, 4, 15, 22, 16],   #a2
                [11, 19, 21, 31, 1, 11, 4, 42, 14, 18],   #a3
                [13, 1, 24, 27, 35, 6, 1, 5, 4, 2],   #a4
                ])

weights = [0.13, 0.1, 0.12, 0.13, 0.07, 0.09, 0.16, 0.08, 0.07, 0.05]

criterias = np.array([True, True, True, True])

t = Topsis(evaluation_matrix, weights, criterias)

t.calc()

print("best_distance\t", t.best_distance)
print("worst_distance\t", t.worst_distance)

# print("weighted_normalized",t.weighted_normalized)

print("worst_similarity\t", t.worst_similarity)
print("rank_to_worst_similarity\t", t.rank_to_worst_similarity())

print("best_similarity\t", t.best_similarity)
print("rank_to_best_similarity\t", t.rank_to_best_similarity())

Step 1
 [[ 7. 15. 12. 34.  9.  2.  5.  8. 40. 17.]
 [ 5. 14. 20. 26.  9.  2.  4. 15. 22. 16.]
 [11. 19. 21. 31.  1. 11.  4. 42. 14. 18.]
 [13.  1. 24. 27. 35.  6.  1.  5.  4.  2.]]

Step 2
 [[0.53846154 0.78947368 0.5        1.         0.25714286 0.18181818
  1.         0.19047619 1.33333333 0.94444444]
 [0.38461538 0.73684211 0.83333333 0.76470588 0.25714286 0.18181818
  0.8        0.35714286 0.73333333 0.88888889]
 [0.84615385 1.         0.875      0.91176471 0.02857143 1.
  0.8        1.         0.46666667 1.        ]
 [1.         0.05263158 1.         0.79411765 1.         0.54545455
  0.2        0.11904762 0.13333333 0.11111111]]

Step 3
 [[0.07       0.07894737 0.06       0.13       0.018      0.01636364
  0.16       0.0152381  0.09333333 0.04722222]
 [0.05       0.07368421 0.1        0.09941176 0.018      0.01636364
  0.128      0.02857143 0.05133333 0.04444444]
 [0.11       0.1        0.105      0.11852941 0.002      0.09
  0.128      0.08       0.03266667 0.05      ]
 [0.13   